## build_single_tree Model of a single tree of Random Forest or Multivariate Random Forest

#### Description

Build a Univariate Regression Tree (for generation of Random Forest (RF) ) or Multivariate Regression
Tree ( for generation of Multivariate Random Forest (MRF) ) using the training samples,
which is used for the prediction of testing samples.
Usage
build_single_tree(X, Y, m_feature, min_leaf, Inv_Cov_Y, Command)
4 build_single_tree

#### Arguments
X Input Feature matrix of M x N, M is the number of training samples and N is the
number of input features
Y Output Feature matrix of M x T, M is the number of training samples and T is
the number of ouput features
m_feature Number of randomly selected features considered for a split in each regression
tree node, which must be positive integer and less than N (number of input
features)
min_leaf Minimum number of samples in the leaf node, which must be positive integer
and less than or equal to M (number of training samples)
Inv_Cov_Y Inverse of Covariance matrix of Output Response matrix for MRF(Input [0 0;0
0] for RF)
Command 1 for univariate Regression Tree (corresponding to RF) and 2 for Multivariate
Regression Tree (corresponding to MRF)

#### Details

The regression tree structure is represented as a list of lists. For a non-leaf node, it contains the
splitting criteria (feature for split and threshold) and for a leaf node, it contains the output responses
for the samples contained in the leaf node.

#### Value
Model of a single regression tree (Univariate or Multivariate Regression Tree). An example of the
list of the non-leaf node:
Flag for determining whether the node is leaf node or branch node. 0 means branch node and 1 means leaf node.
1
Index of samples for the left node
int [1:34] 1 2 4 5 ...
Index of samples for the right node
int [1:16] 3 6 9 ...
Feature for split
int 34
Threshold values for split, average them
num [1:3] 0.655 0.526 0.785
List number for the left and right nodes
num [1:2] 2 3
An example of the list of the leaf node:
Output responses
num[1:4,1:5] 0.0724 0.1809 0.0699 ...
