## plot.subsample Plot Subsampled VIMP Confidence Intervals

#### Description
Plots VIMP (variable importance) confidence regions obtained from subsampling a forest.

#### Usage 
<pre><code>
## S3 method for class 'rfsrc'
plot.subsample(x, alpha = .05,
standardize = TRUE, normal = TRUE, jknife = TRUE,
target, m.target = NULL, pmax = 75, main = "", cex = 1, ...)
</code></pre> 
#### Arguments 
 
x An object obtained from calling subample.
alpha Desired level of significance.
standardize Standardize VIMP? For regression families, VIMP is standardized by dividing
by the variance and then multipled by 100. For all other families, VIMP is scaled
by 100.
normal Use parametric normal confidence regions or nonparametric regions? Generally,
parametric regions perform better.
jknife Use the delete-d jackknife variance estimator?
target For classification families, an integer or character value specifying the class
VIMP will be conditioned on (default is to use unconditional VIMP). For competing
risk families, an integer value between 1 and J indicating the event VIMP
is requested, where J is the number of event types. The default is to use the first
event.
m.target Character value for multivariate families specifying the target outcome to be
used. If left unspecified, the algorithm will choose a default target.
pmax Trims the data to this number of variables (sorted by VIMP).
main Title used for plot.
cex Character expansion used for variable names.
... Further arguments that can be passed to bxp.

#### Author(s)
Hemant Ishwaran and Udaya B. Kogalur



#### Examples 
```{r}
o <- rfsrc(Ozone ~ ., airquality)
oo <- subsample(o)
plot.subsample(oo)
plot.subsample(oo, jknife = FALSE)
plot.subsample(oo, alpha = .01)
plot(oo)
```

#### References

Ishwaran H. and Lu M. (2017). Standard errors and confidence intervals for variable importance in
random forest regression, classification, and survival.
Politis, D.N. and Romano, J.P. (1994). Large sample confidence regions based on subsamples under
minimal assumptions. The Annals of Statistics, 22(4):2031-2050.
Shao, J. and Wu, C.J. (1989). A general theory for jackknife variance estimation. The Annals of
Statistics, 17(3):1176-1197.
plot.survival 25
See Also
subsample
