plot.fRFE Plot function for object of class fRFE
Description
Plot the error rates or MSE of an object of class fRFE which is the result of the functions selectFunctional,
selectGroup and selectLevel.
Usage
## S3 method for class 'fRFE'
plot(x, ...)
Arguments
x An object of class fRFE.
... optional graphical parameters.
Author(s)
Baptiste Gregorutti
plot.importance Plot function for object of class importance
Description
Plot the values of the grouped variable importance which is the result of the function varImpGroup.
Usage
## S3 method for class 'importance'
plot(x, type, horiz, ...)
6 projectWavelet
Arguments
x An object of class importance.
type A string denoting the plot type. Supported types include ‘dotchart’ or ‘bar’.
horiz For barplot only. Should the bars be displayed horizontally (default: TRUE).
... optional graphical parameters.
Author(s)
Baptiste Gregorutti
print.fRFE Print function for object of class fRFE
Description
A print function of an object of class fRFE which is the result of the functions selectFunctional,
selectGroup and selectLevel.
Usage
## S3 method for class 'fRFE'
print(x, ...)
Arguments
x An object of class fRFE.
... optional parameters to be passed to the function ‘summary’.
Author(s)
Baptiste Gregorutti
projectWavelet Projection in a wavelet basis
Description
This function projects a set of curves on a wavelet basis.
Usage
projectWavelet(xdata, wavFilter="s8")
selectFunctional 7
Arguments
xdata A set of n curves of dimension N.
wavFilter A character string denoting the filter type. Supported types include:
EXTREMAL PHASE (daublet): ‘haar’, ‘d2’, ‘d4’, ‘d6’, ‘d8’, ‘d10’, ‘d12’,
‘d14’, ‘d16’, ‘d18’, ‘d20’
LEAST ASYMMETRIC (symmlet): ‘s2’, ‘s4’, ‘s6’, ‘s8’, ‘s10’, ‘s12’, ‘s14’,
‘s16’, ‘s18’, ‘s20’
BEST LOCALIZED: ‘l2’, ‘l4’, ‘l6’, ‘l14’, ‘l18’, ‘l20’
COIFLET: ‘c6’, ‘c12’, ‘c18’, ‘c24’, ‘c30’
Default: ‘s8’.
Value
A matrix of size n × N containing the wavelet coefficients.
Author(s)
Baptiste Gregorutti
References
Percival, D. B. and Walden, A. T., Wavelet Methods for Time Series Analysis (2000), Cambridge
University Press
See Also
hardThresholding,fpca
Examples
data(toyRegFD)
x <- toyRegFD$FDlist[[1]]
design <- projectWavelet(xdata=x)
print(colnames(design))
