toyClassif A toy data of classification
Description
A toy data of classification drawn from a mixture Gaussian distribution. Only the three first variables
are discriminant.
Usage
data(toyClassif)
Format
A list of two components:
• X: the design matrix of size n × p drawn from a mixture Gaussian distribution ;
• Y: the class labels.
toyReg 13
toyReg A toy data of regression
Description
A toy data of regression drawn from a multivariate Gaussian distribution. Only the three first variables
are discriminant.
Usage
data(toyReg)
Format
A list of two components:
• X: the design matrix of size n × p drawn from a multivariate Gaussian distribution ;
• Y: the outcome drawn from the Gaussian distribution.
toyRegFD A functional dataset for regression
Description
A set of 20 functional variables for regression. Only the 8 first variables are predictive.
Usage
data(toyRegFD)
Format
A list of two components:
• FDlist: a list containing the p functional variables, i.e. p matrices of size n × N with n the
number of N-dimensional curves ;
• Y: the outcome drawn from the Gaussian distribution.
References
Gregorutti, B., Michel, B. and Saint Pierre, P. (2014). Grouped variable importance with random
forests and application to multivariate functional data analysis. arXiv:1411.4170
14 varImpGroup

## ``varImpGroup`` A grouped variable importance with Random Forests
Description
A permutation variable importance for groups of variables with Random Forests.
Usage
varImpGroup(object, xdata, ngroups = length(nvarGroup), nvarGroup,
idxGroup, groupsNames = names(nvarGroup),
normalize = (length(unique(nvarGroup)) != 1))

#### Arguments
object A randomForest object.
xdata The input data.
ngroups The number of groups.
nvarGroup The vector of the number of variables in each group.
idxGroup A list of size ‘ngroups’ containing the indexes of each group starting from 0.
groupsNames The group names.
normalize Should the normalized grouped importance measure be computed.
#### Value
An object of class ‘importance’ which is a vector of the importance for each group.

#### Examples

```{r}
data(toyClassif)
attach(toyClassif)
rf <- randomForest(x=X,y=Y,keep.forest=TRUE, keep.inbag=TRUE, ntree=500)
ngroups <- 3
nvarGroup <- c(4,3,6)
idxGroup <- list(c(0,1,2,5), c(2,4,5), c(0,1,5,6,7,8))
grImp <- varImpGroup(rf, X, ngroups, nvarGroup, idxGroup, NULL, normalize=FALSE )
cat("Group importance\n", grImp, "\n")
detach(toyClassif)
```

#### Author(s)
Baptiste Gregorutti

#### References
Gregorutti, B., Michel, B. and Saint Pierre, P. (2015). Grouped variable importance with random
forests and application to multiple functional data analysis, Computational Statistics and Data Analysis
90, 15-35.

#### See Also
selectGroup,selectLevel,selectFunctional,plot.importance
varImpGroup 15
